version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
      resource_class: gpu.nvidia.small
    steps:
      - run: nvidia-smi
      - run: echo 'Working'

workflows:
  my-workflow:
    jobs:
      - build

