version: 2.1

jobs:
  build:
    machine:
      image: cuda-linux-12:default
      resource_class: small
    steps:
      - run: nvidia-smi
      - run: echo 'Working'

workflows:
  my-workflow:
    jobs:
      - build

