version: 2.1

jobs:
  build:
    docker:
       - image: linux-cuda-11:default
    resource_class: gpu.nvidia.small.multi
    steps:
      - run: echo 'Working'

workflows:
  my-workflow:
    jobs:
      - build

